// Demo dispensary search — returns sample dispensary data.
// In production, this would use Google Places API or similar.

export async function searchDispensaries(location, strainNames) {
  // Simulate a brief search delay
  await new Promise(r => setTimeout(r, 1200))
  return generateDemoDispensaries(strainNames)
}

function generateDemoDispensaries(strainNames) {
  return [
    {
      id: 'disp-0',
      name: 'Green Leaf Dispensary',
      address: 'Nearby (enable location for real results)',
      lat: null, lng: null,
      distance: '~2 mi',
      rating: 4.7,
      reviewCount: 234,
      delivery: true,
      deliveryFee: '$5',
      deliveryMin: '$35',
      deliveryEta: '45-60 min',
      matchedStrains: strainNames.slice(0, 2),
      alternativeStrains: [],
      deals: ['20% off first order'],
      priceRange: '$$',
      hours: '9am-9pm',
      phone: '',
      website: '',
      menuUrl: '',
      matchType: 'exact',
    },
    {
      id: 'disp-1',
      name: 'Herbal Wellness Co',
      address: 'Nearby (enable location for real results)',
      lat: null, lng: null,
      distance: '~3 mi',
      rating: 4.5,
      reviewCount: 189,
      delivery: true,
      deliveryFee: null,
      deliveryMin: '$50',
      deliveryEta: '30-45 min',
      matchedStrains: strainNames.slice(1, 3),
      alternativeStrains: [],
      deals: [],
      priceRange: '$$',
      hours: '10am-8pm',
      phone: '',
      website: '',
      menuUrl: '',
      matchType: 'exact',
    },
    {
      id: 'disp-2',
      name: 'The Flower Shop',
      address: 'Nearby (enable location for real results)',
      lat: null, lng: null,
      distance: '~5 mi',
      rating: 4.8,
      reviewCount: 312,
      delivery: false,
      deliveryFee: null,
      deliveryMin: null,
      deliveryEta: null,
      matchedStrains: strainNames.slice(0, 1),
      alternativeStrains: strainNames.slice(3, 4),
      deals: ['Buy 2 get 1 free eighths', 'Happy hour 4-6pm'],
      priceRange: '$$$',
      hours: '9am-10pm',
      phone: '',
      website: '',
      menuUrl: '',
      matchType: 'exact',
    },
    {
      id: 'disp-3',
      name: 'Cloud 9 Cannabis',
      address: 'Nearby (enable location for real results)',
      lat: null, lng: null,
      distance: '~6 mi',
      rating: 4.3,
      reviewCount: 156,
      delivery: true,
      deliveryFee: '$3',
      deliveryMin: '$25',
      deliveryEta: '60-90 min',
      matchedStrains: strainNames.slice(2, 4),
      alternativeStrains: [],
      deals: ['15% off all flower'],
      priceRange: '$',
      hours: '8am-10pm',
      phone: '',
      website: '',
      menuUrl: '',
      matchType: 'exact',
    },
  ]
}
